classDiagram

    PythonLiveAgent --> debugpy
    JavascriptLiveAgent --> js_dap
    PyJSLiveAgent --o PythonLiveAgent
    PyJSLiveAgent --o JavascriptLiveAgent
    class PythonLiveAgent
    class JavascriptLiveAgent
    class PyJSLiveAgent
