services:
  web:
    build: .
    container_name: liverec
    volumes:
      - ./LiveFromDAP:/code
    ports:
      - "8000:5000"
    environment:
      - PWD=/code
      - HOME=/root
      - TERM=xterm
      - SHLVL=1
