sequenceDiagram
    actor User
    User->>Session: select language
    User->>Session: Types code
    Session->>AutoAgent: update_code()
    AutoAgent->>LiveAgent: load_code()
    LiveAgent-->>AutoAgent: code has changed
    AutoAgent-->>Session: code has changed
    Session->>AutoAgent: execute(full_code)
    AutoAgent->>LiveAgent: execute(code, function_to_exec)
    LiveAgent->>DAP: load function
    LiveAgent->>DAP: set breakpoints
    loop Until function exited
        LiveAgent->>DAP: get stack frame
        DAP-->>LiveAgent: stack
        LiveAgent->>DAP: step
    end
    LiveAgent-->>AutoAgent: return results
    AutoAgent-->>Session: return results
    Session-->>User: display results